name: Publish Docker Image to GHCR

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-push-ghcr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile1 --tag ghcr.io/${{ GITHUB_TOKEN }}/pipeline:latest

      - name: Docker Push to GHCR
        run: docker push ghcr.io/${{ GITHUB_TOKEN }}/pipeline:latest



