name: Build and Push to GHCR

on:
  push:
    branches:
      - 'master'  # Adjust the branch as needed

jobs:
  build-and-push-ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: all

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build Docker image
        run: docker build . --file Dockerfile1 --tag ghcr.io/${{ github.actor }}/pipeline:pipeline_image

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.actor }}/pipeline:pipeline_image
